# Generated by Django 5.0.6 on 2024-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_dis',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_gender',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_season',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_wearat',
        ),
        migrations.AddField(
            model_name='products',
            name='dis',
            field=models.TextField(default='None', verbose_name='product description'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('Unisex', 'unisex')], default='gay', max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='image field'),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='Not set', max_length=250, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='products',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='summer', max_length=80, verbose_name='product wear season'),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, choices=[('t-shirt', 'T-shirt'), ('pant', 'Pants'), ('outer', 'Outer'), ('hoodie', 'Hoodie')], max_length=50, verbose_name='product type'),
        ),
        migrations.AddField(
            model_name='products',
            name='wearat',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('weeding', 'Weeding'), ('sports', 'Sports')], max_length=150, verbose_name=''),
        ),
    ]
