# Generated by Django 5.0.6 on 2024-10-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_products_gender_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dis',
            field=models.TextField(verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('Unisex', 'unisex')], max_length=50, verbose_name='Gender specific'),
        ),
        migrations.AlterField(
            model_name='products',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=80, verbose_name='product wear season'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('t-shirt', 'T-shirt'), ('pant', 'Pants'), ('outer', 'Outer'), ('hoodie', 'Hoodie')], max_length=50, verbose_name='product type'),
        ),
        migrations.AlterField(
            model_name='products',
            name='wearat',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('weeding', 'Weeding'), ('sports', 'Sports')], max_length=150, verbose_name='Wear at'),
        ),
    ]
