# Generated by Django 5.0.6 on 2024-10-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_products_dis_alter_products_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to=None, verbose_name='image field'),
        ),
    ]
