# Generated by Django 5.0.6 on 2024-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_products_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.CharField(choices=[('all', 'All'), ('best seller', 'Best seller'), ('season_collection', 'season collection'), ('To be murdered', 'to be murdered')], default='ALL', max_length=250, verbose_name='catogries'),
        ),
    ]
