# Generated by Django 5.0.6 on 2024-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_products_options_products_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0.88, verbose_name='price '),
        ),
    ]
