# Generated by Django 5.0.6 on 2024-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='season',
            field=models.CharField(choices=[('all season', 'All season'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=80, verbose_name='product wear season'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('t-shirt', 'T-shirt'), ('full body set', 'full body set'), ('pant', 'Pants'), ('outer', 'Outer'), ('hoodie', 'Hoodie')], max_length=50, verbose_name='product type'),
        ),
        migrations.AlterField(
            model_name='products',
            name='wearat',
            field=models.CharField(choices=[('casual', 'Casual'), ('comic', 'Comic'), ('formal', 'Formal'), ('party', 'Party'), ('weeding', 'Weeding'), ('sports', 'Sports'), ('others', 'Others')], max_length=150, verbose_name='Wear at'),
        ),
    ]
