# Generated by Django 5.0.6 on 2024-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_products_season_alter_products_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=450)),
                ('image', models.ImageField(upload_to=None)),
                ('bill_amt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='catagory',
            field=models.CharField(choices=[('all', 'All'), ('best seller', 'Best seller'), ('season collection', 'season collection'), ('to be murdered', 'to be murdered'), ('new arival', 'New Arival')], default='ALL', max_length=250, verbose_name='catogries'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dis',
            field=models.TextField(blank=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='media/', verbose_name='image field'),
        ),
    ]
